### ISSUE TITLE
Can you add back something

### ISSUE THREAD

**Issue by OfficialLilKev** [poggit-orphanage/FactionsPro_1.4#10]
Can you add back /f topfactions back plz

**Comment by Awzaw** [comment]
I don't think that command was ever in this version of the original FactionsPro, but I'll add that today if I have time

**Comment by Awzaw** [comment]
FactionsPro1.4 doesn't have faction 'strength' at all, maybe you should use the original FactionsPro instead?

**Comment by OfficialLilKev** [comment]
Ok
