### ISSUE TITLE
PureChat and FactionPro doesn't work

### ISSUE THREAD

**Issue by CupidonSauce173** [poggit-orphanage/FactionsPro_1.4#11]
Faction name doesn't show in the name. I use the last plugin with the last purechat

how to reproduce this issue
1.Download PureChat and FactionsPro_1,4
2.Drop them in the plugins files
3.Set in PureChat the default plugin for factions : FactionsPro
4. Restart or reload the server

**Comment by Awzaw** [comment]
I can't reproduce this - can you provide the list of plugins you are using?
