### ISSUE TITLE
PureChat and FactionsProBeta does not Work together

### ISSUE THREAD

**Issue by Wertzui123** [poggit-orphanage/FactionsPro_1.4#15]
PureChat always says "no valid factions Plugin found" when i write FactionsProBeta in the config.yml but if I use FactionsPro and write this in the config.yml of pure chat it works. But I wan't to use FactionsProBeta. Can ayone help me?

**Comment by Awzaw** [comment]
For future reference, both versions require `FactionsPro` in the config.
