### ISSUE TITLE
errors on run

### ISSUE THREAD

**Issue by DroidPlaysM** [poggit-orphanage/FactionsPro_1.4#4]
Error: "Class 'SQLite3' not found" (EXCEPTION) in "FactionsPro.phar/src/FactionsPro/FactionMain" at line 91
Error: "Call to a member function close() on null" (EXCEPTION) in "FactionsPro.phar/src/FactionsPro/FactionMain" at line 453

**Comment by Awzaw** [comment]
You need to make sure you've got the sqlite extension enabled in PHP, either by getting the right binary from http://pmmp.readthedocs.io/en/rtfd/installation.html, and/or by enabling it in php.ini
